language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true

env:
  global:
    - BLPAPI_ROOT = /home/bbg

install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov flake8 codecov
  - python setup.py install

script:
  - flake8 --extend-ignore=E701,E501 xbbg
  - pytest --doctest-module --cov -v xbbg

after_success:
  - coverage report
  - cat .coverage
  - codecov --token=ff17768d-30bd-4917-98f2-a011606597ea
